links:
  - name: CK's Notepad
    url: https://blog.kevinyang.net/
  - name: The Will Will Web | Will 保哥
    url: https://blog.miniasp.com/
  - name: 全端開發人員天梯
    url: https://wellwind.idv.tw/blog/
  - name: POY CHANG | Trial and Error
    url: https://poychang.github.io/
  - name: Duran 的技術冶煉廠
    url: https://dog0416.blogspot.com/
  - name: 凱哥打扣
    url: https://kyleap.github.io/
  - name: CSS可樂
    url: http://csscoke.com
  - name: 黑暗執行緒
    url: https://blog.darkthread.net/
  - name: 余小章 @ 大內殿堂
    url: https://www.dotblogs.com.tw/yc421206
  - name: Jeff Wu's Note
    url: https://blog.crazyalu.com/
social:
- slug: github
  url: https://github.com/jiaming0708
- slug: twitter
  url: https://twitter.com/Secret_GoGo
- slug: rss
  url: /atom.xml
giscus:
  enable: true
  repo: jiaming0708/jiaming0708.github.io # Github repository name
  repo_id: MDEwOlJlcG9zaXRvcnk4Mjc2OTM4OQ== # Github repository id
  category: Q&A # Github discussion category
  category_id: DIC_kwDOBO717c4B_0N9 # Github discussion category id
  # Available values: pathname | url | title | og:title
  mapping: title
  # Available values: 0 | 1 
  reactions_enabled: 1
  # Available values: light | dark | dark_high_contrast | transparent_dark | preferred-color-scheme
  theme: light
# widgets
widgets:
  - about
  - links
  - tagcloud
  - categories