name: Send Message on discussions comment.
permissions:
  contents: read
  pull-requests: write

on:
  discussion_comment:
    types: [created]

jobs:
  sendMessage:
    runs-on: ubuntu-latest

    steps:
      - name: send discord message
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "content": "**New Discussion Comment**\n**From:** ${{ github.event.sender.login }}\n**Title:** ${{ github.event.discussion.title }}\n**Link:** ${{ github.event.comment.html_url }}\n**Body:**\n```\n${{ github.event.comment.body }}\n```"
               }' \
               ${{ secrets.DISCORD_WEBHOOK }}